Algoritmo "LerMatriz"

Var
mat: vetor [1..3, 1..2] de inteiro
l, c: inteiro

Inicio
Para l <- 1 ate 3 faca
     Para c <- 1 ate 2 faca
          Escreva ("Digite o valor da posição [", 1, ",", c, "]: ")
          Leia (mat[l,c])
     Fimpara
Fimpara

Para l <- 1 ate 3 faca
     Para c <- 1 ate 2 faca
          Escreva (mat[l,c])
     Fimpara
     Escreval ()
Fimpara



Fimalgoritmo