Algoritmo "Contar com salto"

Var
valor, contador, salto: inteiro

Inicio
contador <- 0
Escreva ("Quer contar até quanto? ")
Leia (valor)
Escreva ("Qual o valor do salto? ")
Leia (salto)
enquanto (contador<=valor) faça
         Escreval (contador)
         contador <- contador+salto
         fimenquanto
         Escreval ("Terminei de contar.")
//por exemplo contar de 0 a 100 de 5 em 5

Fimalgoritmo