algoritmo "Comparar números"

var
N1, N2: inteiro

inicio
Escreva ("Digite o primeiro número: ")
Leia (N1)
Escreva ("Digite o segundo número: ")
Leia (N2)
se (N1>N2) entao
Escreva ("O primeiro valor é o maior.")
fimse
     Se (N2>N1) entao
     Escreva ("O segundo valor é o maior.")
     fimse
          Se (N1=N2) entao
          Escreva ("Não existe valor maior, os dois são iguais.")
          fimse
     
fimalgoritmo
