Algoritmo "Contar com salto"

Var
pvalor, valor, contador, incremento: inteiro

Inicio
contador
Escreva ("Digite o primeiro valor: ")
Leia (pvalor)
Escreva ("Digite o último valor: ")
Leia (valor)
Escreva ("Digite o incremento: ")
Leia (incremento)
enquanto (contador<=valor) faça
         Escreval (contador)
         contador <- pvalor+incremento
         fimenquanto
         Escreval ("Acabou!")
//por exemplo contar de 0 a 100 de 5 em 5

Fimalgoritmo