Algoritmo "Contar com salto e soma 2"

Var
valor, contador, salto, S: inteiro

Inicio
contador <- 500
S <- 0
Escreva ("Quer contar até quanto? ")
Leia (valor)
Escreva ("Qual o valor do salto? ")
Leia (salto)
enquanto (contador>=valor) faça
         Escreval (contador)
         contador <- contador-salto
         S <- S+(contador+SALTO)
         fimenquanto
         Escreval   ("A soma de todos os valores foi: ", S)



Fimalgoritmo