algoritmo "FUNÇÕES ARITMÉTICAS"
var
valorabs, expon, intei, raiz, pih, seno, cosseno, tangente, grau: real
inicio
valorabs<- Abs(-10)
Escreval(valorabs)
expon<- exp(3,2)
Escreval (expon)
intei<- int(3.9)
Escreval (intei)
raiz<- raizq(25)
Escreval (raiz)
pih<- pi
Escreval (pih)
seno<- sen(0.523)
Escreval(seno)
cosseno<- cos(0.523)
Escreval (cosseno)
tangente<- tan(0.523)
Escreval (tangente)
grau <- grauprad(30)
Escreval (grau)

fimalgoritmo
