algoritmo "Conversor de distância"

var
 metros, km, hm, dam, dm, cm, mm: real
 
inicio
Escreva ("Digite uma distância em metros: ")
Leia (metros)
km<- metros/1000
hm<- metros/100
dam<- metros/10
dm<- metros/0.1
cm<- metros/0.01
mm<- metros/0.001
Escreval("A distância de ",metros," metros corresponde a: ")
Escreval (km,"km ")
Escreval (hm, "hm ")
Escreval (dam, "dam ")
Escreval (dm, "dm ")
Escreval (cm, "cm ")
Escreval (mm, "mm ")

fimalgoritmo
