Algoritmo "Temperatura"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2022
Var
   F, C: real

Inicio

      Escreva ("Qual a temperatura aqui?")
      Leia (F)
      C <- (F-32)/1.8
      Escreva ("No Brasil estaria: ", C:4:1)
      // C:4:1 usa quatro casas depois da vírgula e arredonda pra uma casa

Fimalgoritmo